spring:
  datasource:
    url: jdbc:sqlite:mydatabase.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
  sql:
    init:
      mode: always
      platform: sqlite
